using System.Runtime.CompilerServices;
using BepInEx.Bootstrap;
using LethalConfig;
using LethalConfig.AutoConfig;
using LethalConfig.Mods;
using LethalConfig.Utils;

namespace BepInExFasterLoadAssetBundles.Helpers;

internal static class LethalConfigHelper
{
    // Special thanks to Dawn team for this code on how to register runtime config
    // https://github.com/TeamXiaolan/DawnLib/blob/1.0/DawnLib.Dusk/src/Internal/ModCompats/DuskLethalConfigCompat.cs

    public static bool IsEnabled => Chainloader.PluginInfos.ContainsKey("ainavt.lc.lethalconfig");

    [MethodImpl(MethodImplOptions.NoInlining | MethodImplOptions.NoOptimization)]
    public static void RegisterConfig()
    {
        var modInformation = new ModInfo()
        {
            Name = nameof(BepInExFasterLoadAssetBundlesPatcher),
            Guid = nameof(BepInExFasterLoadAssetBundlesPatcher),
            Version = typeof(BepInExFasterLoadAssetBundlesPatcher).Assembly.GetName().Version.ToString(),
            Description = "Makes start up loading time faster",
            Icon = Assets.DefaultModIcon // todo?
        };
        var mod = new Mod(modInformation);
        LethalConfigManager.Mods.Add(modInformation.Guid, mod);

        var baseConfigItem = AutoConfigGenerator.GenerateConfigForEntry(Patcher.ConfigManager.CacheRetentionDays);
        if (baseConfigItem != null)
        {
            baseConfigItem.IsAutoGenerated = true;
            baseConfigItem.Owner = mod;
            mod.ConfigItems.Add(baseConfigItem);
        }
    }
}
