<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <WarningsAsErrors>Nullable</WarningsAsErrors>
    <LangVersion>latest</LangVersion>
    <RestoreAdditionalProjectSources>
        https://api.nuget.org/v3/index.json;
        https://nuget.bepinex.dev/v3/index.json;
        https://nuget.windows10ce.com/nuget/v3/index.json;
    </RestoreAdditionalProjectSources>
    <RootNamespace>BepInExFasterLoadAssetBundles</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Version>0.0.0</Version>
  </PropertyGroup>

  <PropertyGroup>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>embedded</DebugType>
    <PathMap>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)'))=./</PathMap>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Core" Version="5.*" PrivateAssets="all" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" PrivateAssets="all" />
    <PackageReference Include="UnityEngine.Modules" Version="2022.3.9" PrivateAssets="all" />
    <PackageReference Include="AinaVT-LethalConfig" Version="1.*" PrivateAssets="all" />  
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.2" PrivateAssets="all" />
		<Publicize Include="LethalConfig">
			<PublicizeTarget>all</PublicizeTarget>
			<PublicizeCompilerGenerated>false</PublicizeCompilerGenerated>
			<IncludeOriginalAttributesAttribute>false</IncludeOriginalAttributesAttribute>
			<Strip>false</Strip>
		</Publicize>
	</ItemGroup>

  <ItemGroup>
    <None Include="..\CHANGELOG.md" />
  </ItemGroup>

  <Target Name="CopyPublishFiles" AfterTargets="AfterBuild">
    <ItemGroup>
      <PublishFiles Include="$(MSBuildThisFileDirectory)Publish/*.*" />
    </ItemGroup>

    <!-- Copies icon.png and manifest.json -->
    <Copy SourceFiles="@(PublishFiles)" DestinationFolder="$(OutDir)" Condition="@(PublishFiles-&gt;Count()) != 0" />
  </Target>

</Project>
